app = "api-ks-web-scraper"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
primary_region = "arn"

[env]
  PORT = "8080"
  PRIMARY_REGION = "arn"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  processes = ["app"]
  protocol = "tcp"
  #TODO: Kom ihåg att auto start / stop gör att "riktig" scraper inte fungerar
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
