app = "api-ks-web-scraper"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "arn"

[env]
  PORT = "8080"
  PRIMARY_REGION = "arn"

[processes]
app = 'run -A src/main.ts'

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  size = "shared-cpu-1x"
